Make rc-trigger compatible with Inferno/Preact
When using Inferno instead of React, I'm getting the following error when closing a dropdown:

Uncaught TypeError: this._component.getPopupDomNode is not a function
    at Object.onPopupMouseLeave (index.js:178)

This change should fix the bug. I guess it's also related to https://github.com/ant-design/ant-design/issues/5701